name: Deploy and Run K6 Tests on Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Docker Image, Deploy to Kubernetes, and Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/test:latest

     # Step 5: Apply Kubernetes configurations
      - name: Start Minikube
        run: |
          minikube start --driver=none
          kubectl cluster-info

      # Step 6: Apply Kubernetes configurations
      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f influxdeployment.yml
          kubectl apply -f k6deployment.yml

      # Step 7: Verify Pods
      - name: Verify Pods
        run: |
          kubectl get pods
          kubectl wait --for=condition=ready pod -l app=k6-runner --timeout=300s

      # Step 8: Run K6 Test
      - name: Run K6 Test
        run: |
          POD_NAME=$(kubectl get pods -l app=k6-runner -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD_NAME -f

      # Step 9: Clean up 
      - name: Clean Up Resources
        if: always()
        run: |
          kubectl delete -f k6deployment.yml
          kubectl delete -f influxdeployment.yml
