name: Deploy and Run K6 Tests on Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Docker Image, Deploy to Kubernetes, and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/test:latest
          
      - name: Install conntrack
        run: sudo apt-get update && sudo apt-get install -y conntrack
        
      - name: Start Minikube
        run: |
         sudo  minikube start --driver=none
         sudo  kubectl cluster-info

      - name: Apply Kubernetes Configurations
        run: |
          kubectl apply -f influxdbdeployment.yml
          kubectl apply -f k6deployment.yml

      - name: Verify Pods
        run: |
          kubectl get pods
          kubectl wait --for=condition=ready pod -l app=k6-runner --timeout=300s

      - name: Run K6 Test
        run: |
          POD_NAME=$(kubectl get pods -l app=k6-runner -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD_NAME -f

      - name: Clean Up Resources
        if: always()
        run: |
          kubectl delete -f k6deployment.yml
          kubectl delete -f influxdbdeployment.yml
